### ISSUE TITLE
screen reactivity on android devies

### ISSUE THREAD

**Issue by talllons** [geopaparazzi/smash#173] opened 2022-03-10 11:34 UTC
I don't know if other users of smash (1.7.2) for android have my problems, but the drawing and change of geopackages features is severely limited by the poor reactivity of the screen in the operations of selecting and dragging points and vertices and also the measurement tool is practically unusable.
By using a (bluetooth) mouse is possible to mitigate the problem, and is possible to change the position of points and use the measurement tool.
Instead, with the fingers, attempts to select pre-existing points almost always lead to the appearance of the dialog related to the geopackages layer where to insert new elements, while the query features tool works without problems and correctly selects the points or vertices.
I don't know if certain configuration parameters must be set but the different devices that I have tried and that exhibit this problem work fine with other similar mapping apps.
In my opinion, a further aspect that complicates the drawing of new geometries is related to the fact that a slightly longer pressure is often interpreted as a request to delete the points and it can also happen that lines and polygons disappear completely during the drawing.
As a possible future option, it could perhaps be convenient to allow to choose whether to use the long press to delete the nodes or an alternative method, perhaps with an extra step but more stable as management. 

Cheers

Sergio

**Comment by moovida** [comment] 2022-03-14 10:17
Hi @talllons , can you give me an example dataset to reproduce the problem? Are these huge polygons?

I am not experiencing this issue, but then I am also not doing big dataset editing on mobile.

**Comment by moovida** [comment] 2022-03-15 07:35
Hi @talllons , no need for a dataset, I have been able to reproduce the issue. It was due to a bug that has been fixed. 
Will be in the next release.

**Closed by moovida** 2022-03-15 07:35 UTC
Labels: bug

**Comment by moovida** [comment] 2022-03-15 08:24
Make sure you follow issue #174

**Comment by talllons** [comment] 2022-03-15 10:30
Hi Antonello,
many thanks for your reply.  I was pretty sure it was a bug because with Smash I was able to load and manage geological data files with about  20,000 points and 1,500 polygons without problems. 
Cheers
Sergio
