### ISSUE TITLE
Mandatory text fields can be empty

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#130] opened 2021-06-30 13:48 UTC
Is it by design?

**Comment by moovida** [comment] 2021-07-14 08:20
Nope, this is a bug or better a migration point that is still open. If a constraint is not fulfilled, at the current time the user sees it in red, but the note is still saved. It probably should not. I will keep this open as a reminder.

**Comment by moovida** [comment] 2024-02-29 08:00
This has no been discussed many times and there is no clear idea about it. Sure is that in the field you  want to be able to save a note and complete it later if you need to do so. Therefore for now, let's call this "by design".
I think this might be something to think of for the serverside. When uploading, a check should be done on mandatory elements.
But this is something to be done on a budget. For now closing this.

**Closed by moovida** 2024-02-29 08:00 UTC
Labels: enhancement
