### ISSUE TITLE
Not working on Ungoogle/Degoogle Android phone

### ISSUE THREAD

**Issue by kikislater** [geopaparazzi/smash#84] opened 2020-12-03 06:44 UTC
Nice project, I would like to test, I installed it but it doesn't work on /e/OS which is an android version without google based on LineageOS released. 

App stucks on Welcome screen with checklist of multiple tasks. I think app rely on Google location service (replaced in /e/OS by Mozilla location service). In /e/ we have MicroG service which allow some app to work with required google service but smash doesn't seem to deal with it. Any idea how to solve it ?

**Comment by moovida** [comment] 2020-12-03 07:00
Hi @kikislater , I wasn't aware that it would freeze due to google services missing. I want to absolutely solve this if you can help me a bit further.

Some comments/notes:

* can you confirm me that you installed latest version 1.6.2? We solved a startup freezing issue on some devices for that version.
* I know the GPS library can make use of g-services. But I thought it "could", so I assumed it would without services.
* How difficult would it be to install /e/OS on a Pixel 2XL? I might give it a try to reproduce this, if necessary. But I can't spend a whole day on just installing :-)

So if you are up to help me, let's start discussing.

**Comment by kikislater** [comment] 2020-12-03 12:45
I'm not sure about google service but I suspect it ! 

No it was 1.6.0. 1.6.2 installed from Aurora Store (allow to access play store from /e/OS). Nice one step more now, thank you ! But location still not work. I have allow app to use location and storage.

How Gpshandler and geolocator work ? 

Pretty easy to install if you already know how to install custom android rom (it's even faster and simplier : no need for magisk or crap things like that) ... There is an official build now for Pixel 2 XL : https://doc.e.foundation/devices/taimen/

Instructions to install as follow : https://doc.e.foundation/devices/taimen/install 

I don't want to waste your time installing /e/OS ... May be I could debug myself remotely if you have some ideas.

**Comment by moovida** [comment] 2020-12-03 12:52
> How Gpshandler and geolocator work ?

What do you mean exactly? If you gave the two permissions and have the gps switched on, you should see an orange colored icon in the bottom center gps center icon (the bigger one between the other icons). That means it works and is looking for a fix.
What is the problem you are experiencing?

Regarding /e/OS, it look like rather simple to install. I will not do it very soon, but will try to as soon as I have time.

**Comment by kikislater** [comment] 2020-12-03 13:02
I'm not getting GPS fix from onboard GPS device. Other app launch geolocation icon near network icon whereas with smash it's not the case !

![Uploading Screenshot_20201203-165613_Bliss_Launcher.png…]()


![Screenshot_20201203-165700_SMASH](https://user-images.githubusercontent.com/13238064/101021029-cad96000-3588-11eb-9226-b118c2065f7e.png)

**Comment by moovida** [comment] 2020-12-03 13:15
This might indeed be due to the google services. 
Can you look in the settings -> Diagnostics and check if there are errors in the log.

That said, in the gps library, there is an issue about this: https://github.com/rekab-app/background_locator/issues/111
and it seems there is a fix already in the master branch.

I could do the required change to use the latest gps library code form git.
So here comes the question:

* are you able to build SMASH from source and would be able to test this?
* or would you rather have a temporary apk sent to you to test that?

**Comment by kikislater** [comment] 2020-12-03 13:29
Thank you for looking up to related problem. 
I could build myself but not this week. Apk is Ok of course

**Comment by moovida** [comment] 2020-12-03 13:30
I am in the progress of building it. Will post the apk link here. Thank you.

**Comment by moovida** [comment] 2020-12-03 13:40
Here it goes: https://we.tl/t-7aVIlWpduM
I have to go into a meeting now, but will be happy to read your results (fingers crossed).

**Comment by kikislater** [comment] 2020-12-03 14:19
Perfect it works ! 

![Screenshot_20201203-181319_SMASH](https://user-images.githubusercontent.com/13238064/101032522-5821b200-3593-11eb-9f8a-8722172404ce.png)


When I create a new project, it stay on blue screen step 1/11 (kind of tutorial) and nothing able to do. Just force close app, reopen project works. May be another issue ...

Thank you. When released I will add smash compatible to eOS community thread

**Comment by moovida** [comment] 2020-12-03 17:54
Great, let me leave this open to:

* ask you later about the coach markers freeze issue
* update with new release

**Comment by kikislater** [comment] 2020-12-03 17:56
Ok seems good !

**Comment by moovida** [comment] 2023-08-16 14:28
Closing as done I guess. :-)

**Closed by moovida** 2023-08-16 14:28 UTC
Labels: bug
